### ISSUE TITLE
Sorting recipes does not work 

### ISSUE THREAD

**Issue by irrationalRock** [666PRJ/CookingCurator#183]

**Comment by hjpatel16** [comment]
Sorting does work. Why is this issue created @irrationalRock ?

**Comment by hjpatel16** [comment]
Accidentally closed the issue

**Comment by irrationalRock** [comment]
Just for reference.

The top two results should not be at the top

![image](https://user-images.githubusercontent.com/16523071/55524124-2dfb4c80-565a-11e9-9a29-d624a2c5082f.png)

**Comment by hjpatel16** [comment]
We will be re-adding those two recipes. If it still doesn't work we will take both recipes down

**Comment by irrationalRock** [comment]
Closed but will file a issue for the true cause
